version: '20.10.21'

services:
  nodejs:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: colinzhou.node-example
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    depends_on:
      - mysql

  mysql:
    image: mysql
    env_file: ./.env
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    container_name: mydb