version: '20.10.21'

services:
  mysql:
    image: mysql:5.7.24
    env_file: ./.env
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./wordament_user.sql:/docker-entrypoint-initdb.d/wordament_user.sql
      - ./wordament_scores.sql:/docker-entrypoint-initdb.d/wordament_scores.sql  
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    container_name: mydb
  
  nodejs:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: colinzhou.node-example
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    depends_on:
      mysql:
        condition: service_started


